//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebForm1.myWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="myWebService.WebServiceTestSoap")]
    public interface WebServiceTestSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 HelloWorldResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        WebForm1.myWebService.HelloWorldResponse HelloWorld(WebForm1.myWebService.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<WebForm1.myWebService.HelloWorldResponse> HelloWorldAsync(WebForm1.myWebService.HelloWorldRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 input 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Getstring", ReplyAction="*")]
        WebForm1.myWebService.GetstringResponse Getstring(WebForm1.myWebService.GetstringRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Getstring", ReplyAction="*")]
        System.Threading.Tasks.Task<WebForm1.myWebService.GetstringResponse> GetstringAsync(WebForm1.myWebService.GetstringRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public WebForm1.myWebService.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(WebForm1.myWebService.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebForm1.myWebService.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(WebForm1.myWebService.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetstringRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Getstring", Namespace="http://tempuri.org/", Order=0)]
        public WebForm1.myWebService.GetstringRequestBody Body;
        
        public GetstringRequest() {
        }
        
        public GetstringRequest(WebForm1.myWebService.GetstringRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetstringRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string input;
        
        public GetstringRequestBody() {
        }
        
        public GetstringRequestBody(string input) {
            this.input = input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetstringResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetstringResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebForm1.myWebService.GetstringResponseBody Body;
        
        public GetstringResponse() {
        }
        
        public GetstringResponse(WebForm1.myWebService.GetstringResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetstringResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetstringResult;
        
        public GetstringResponseBody() {
        }
        
        public GetstringResponseBody(string GetstringResult) {
            this.GetstringResult = GetstringResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceTestSoapChannel : WebForm1.myWebService.WebServiceTestSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceTestSoapClient : System.ServiceModel.ClientBase<WebForm1.myWebService.WebServiceTestSoap>, WebForm1.myWebService.WebServiceTestSoap {
        
        public WebServiceTestSoapClient() {
        }
        
        public WebServiceTestSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceTestSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceTestSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceTestSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebForm1.myWebService.HelloWorldResponse WebForm1.myWebService.WebServiceTestSoap.HelloWorld(WebForm1.myWebService.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            WebForm1.myWebService.HelloWorldRequest inValue = new WebForm1.myWebService.HelloWorldRequest();
            inValue.Body = new WebForm1.myWebService.HelloWorldRequestBody();
            WebForm1.myWebService.HelloWorldResponse retVal = ((WebForm1.myWebService.WebServiceTestSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebForm1.myWebService.HelloWorldResponse> WebForm1.myWebService.WebServiceTestSoap.HelloWorldAsync(WebForm1.myWebService.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebForm1.myWebService.HelloWorldResponse> HelloWorldAsync() {
            WebForm1.myWebService.HelloWorldRequest inValue = new WebForm1.myWebService.HelloWorldRequest();
            inValue.Body = new WebForm1.myWebService.HelloWorldRequestBody();
            return ((WebForm1.myWebService.WebServiceTestSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebForm1.myWebService.GetstringResponse WebForm1.myWebService.WebServiceTestSoap.Getstring(WebForm1.myWebService.GetstringRequest request) {
            return base.Channel.Getstring(request);
        }
        
        public string Getstring(string input) {
            WebForm1.myWebService.GetstringRequest inValue = new WebForm1.myWebService.GetstringRequest();
            inValue.Body = new WebForm1.myWebService.GetstringRequestBody();
            inValue.Body.input = input;
            WebForm1.myWebService.GetstringResponse retVal = ((WebForm1.myWebService.WebServiceTestSoap)(this)).Getstring(inValue);
            return retVal.Body.GetstringResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebForm1.myWebService.GetstringResponse> WebForm1.myWebService.WebServiceTestSoap.GetstringAsync(WebForm1.myWebService.GetstringRequest request) {
            return base.Channel.GetstringAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebForm1.myWebService.GetstringResponse> GetstringAsync(string input) {
            WebForm1.myWebService.GetstringRequest inValue = new WebForm1.myWebService.GetstringRequest();
            inValue.Body = new WebForm1.myWebService.GetstringRequestBody();
            inValue.Body.input = input;
            return ((WebForm1.myWebService.WebServiceTestSoap)(this)).GetstringAsync(inValue);
        }
    }
}
